# Generated by Django 3.2.3 on 2021-11-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=500)),
                ('overview', models.TextField()),
                ('vote_average', models.FloatField()),
                ('original_title', models.CharField(max_length=100)),
                ('genrename', models.TextField()),
                ('actorname', models.TextField()),
                ('actors', models.ManyToManyField(related_name='movie_actor', to='movies.Actor')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
